/** @type {import('prettier').Config & import('prettier-plugin-tailwindcss').options & import('@ianvs/prettier-plugin-sort-imports')} */
const config = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^types$",
    "^@/types/(.*)$",
    "",
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "^(next-auth/(.*)$)|^(next-auth$)",
    "^(better-auth/(.*)$)|^(better-auth$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/server/(.*)$",
    "^(drizzle-orm/(.*)$)|^(next$)",
    "",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "",
    "^@/hooks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^(@/(?:[^/]+/)?_components|./_components)/(.*?)$",
    "^@/registry/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "^@/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrderParserPlugins: ["typescript", "jsx", "tsx"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  tailwindFunctions: [
    "clsx",
    "tw",
    "apply",
    "theme",
    "variants",
    "e",
    "screen",
    "cn",
  ],
}

export default config
