import type { Metadata } from "next"

import "@/styles/globals.css"

import { ibmMono, ibmSans } from "@/config/fonts"

import { RootProvider } from "@/components/providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmSans.variable} ${ibmMono.variable} antialiased`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  )
}
